"""Standard output directory manager for `quant_exp` runs.

Layout
------
    results/
        <timestamp>_<experiment>_<mode>/
            config.yaml             # resolved ExperimentConfig
            metrics.json            # final metrics (paper-friendly)
            report.html             # self-contained HTML report (if --report)
            log.txt                 # execution log (if enabled)
        latest -> <timestamp>_<experiment>_<mode>/  (symlink)
"""

from __future__ import annotations

import html
import json
import platform
import sys
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any, Sequence, Union

import yaml

from quant_lib.utils.git import get_git_commit

if TYPE_CHECKING:
    from quant_lib.experiments.base import ExperimentConfig


_RESULTS_DIR = Path("results")


# ─────────────────────────────────────────────────────────────────────
# HTML report rendering helpers
# ─────────────────────────────────────────────────────────────────────


# Self-contained CSS + skeleton for a single-file report. All charts
# are embedded as base64 data URIs (no external file references).
# The {subtitle_block} placeholder is empty when no subtitle is given.
_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
        max-width: 1200px; margin: 2em auto; padding: 0 1.5em; color: #222; line-height: 1.5; }}
h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 0.3em; }}
h2 {{ color: #34495e; margin-top: 2em; border-bottom: 1px solid #ecf0f1; padding-bottom: 0.2em; }}
table {{ border-collapse: collapse; width: 100%; margin: 1em 0; font-size: 0.95em; }}
th, td {{ border: 1px solid #ddd; padding: 6px 10px; text-align: left; }}
th {{ background: #f4f6f8; font-weight: 600; }}
tr:nth-child(even) {{ background: #fafbfc; }}
.kv-label {{ font-weight: 600; width: 200px; }}
.chart {{ margin: 1.5em 0; }}
.chart img {{ max-width: 100%; height: auto; border: 1px solid #ecf0f1; border-radius: 4px; }}
code {{ background: #f4f6f8; padding: 2px 4px; border-radius: 3px; font-size: 0.9em; }}
.footer {{ color: #7f8c8d; font-size: 0.85em; margin-top: 3em; border-top: 1px solid #ecf0f1; padding-top: 1em; }}
</style>
</head>
<body>
<h1>{title}</h1>
{subtitle_block}
{body}
<div class="footer">Generated by quant_exp on {timestamp}</div>
</body>
</html>
"""


def _render_table(rows: Sequence[Sequence[Any]]) -> str:
    """Render a 2D iterable as an HTML table.

    The first row is treated as the header. Cell values are HTML-escaped
    and converted to str. None renders as an empty cell.
    """
    rows = list(rows)
    if not rows:
        return "<p><em>No data.</em></p>"
    out = ["<table>"]
    out.append("<thead><tr>")
    for cell in rows[0]:
        out.append(f"<th>{html.escape(str(cell)) if cell is not None else ''}</th>")
    out.append("</tr></thead>")
    out.append("<tbody>")
    for row in rows[1:]:
        out.append("<tr>")
        for cell in row:
            out.append(f"<td>{html.escape(str(cell)) if cell is not None else ''}</td>")
        out.append("</tr>")
    out.append("</tbody></table>")
    return "\n".join(out)


def _render_kv(pairs: Sequence[tuple]) -> str:
    """Render a key-value list as a 2-column table.

    ``pairs`` is an iterable of (key, value) tuples. Both are HTML-escaped.
    """
    out = ["<table>"]
    for k, v in pairs:
        out.append(
            f"<tr><td class='kv-label'>{html.escape(str(k))}</td>"
            f"<td>{html.escape(str(v)) if v is not None else ''}</td></tr>"
        )
    out.append("</table>")
    return "\n".join(out)


def _render_chart(b64_or_path: str) -> str:
    """Render a chart. Accepts either a base64 data URI or a relative path.

    A data URI is embedded inline. A plain path is referenced as a
    relative image (so the report directory remains a portable bundle
    when charts are saved as separate files).
    """
    if not b64_or_path:
        return "<p><em>Chart not available.</em></p>"
    if b64_or_path.startswith("data:"):
        return f'<div class="chart"><img src="{b64_or_path}" alt="chart"></div>'
    return (
        f'<div class="chart"><img src="{html.escape(b64_or_path)}" alt="chart"></div>'
    )


def _render_section(heading: str, content: Union[str, dict, list, tuple]) -> str:
    """Render one report section.

    ``content`` can be:
    - str: rendered as raw HTML (caller's responsibility to escape)
    - dict: rendered as a key-value table
    - list of 2-tuples: rendered as a key-value table
    - list of lists: rendered as a multi-row table (first row = header)
    - tuple (str, Any): for ``("table", rows)``, ``("kv", pairs)``,
      ``("chart", b64_or_path)``, or ``("html", raw_html)`` for explicit
      dispatch. This lets the caller mix types unambiguously.
    """
    h = f"<h2>{html.escape(heading)}</h2>"
    if isinstance(content, str):
        return h + content
    if isinstance(content, dict):
        return h + _render_kv(list(content.items()))
    if isinstance(content, tuple) and len(content) == 2 and isinstance(content[0], str):
        kind, payload = content
        if kind == "table":
            return h + _render_table(payload)
        if kind == "kv":
            return h + _render_kv(payload)
        if kind == "chart":
            return h + _render_chart(payload)
        if kind == "html":
            return h + payload
    if isinstance(content, list):
        if all(isinstance(item, tuple) and len(item) == 2 for item in content):
            return h + _render_kv(content)
        return h + _render_table(content)
    return h + f"<p>{html.escape(str(content))}</p>"


def _safe_mklink(link: Path, target: str) -> None:
    """Create or update a symlink. Cross-platform safe.

    Sprint 2 fix 2.7: previously the OSError fallback wrote a "LATEST"
    marker file but no code in the framework ever read it -- so the
    fallback was effectively dead code. The fallback is now actually
    USED by ``read_latest_run_dir()`` below: a Windows user without
    admin (where symlinks fail) can still programmatically discover the
    most recent run directory. Use ``read_latest_run_dir()`` instead
    of trying to ``Path.readlink()`` directly so the symlink-or-marker
    fallback works transparently.

    The marker file is named ``LATEST`` (uppercase, no extension) so it
    stands out in a directory listing and doesn't conflict with
    user-named files.
    """
    try:
        if link.is_symlink() or link.exists():
            link.unlink()
        # Use relative target for portability
        link.symlink_to(target)
    except OSError:
        # Some filesystems (e.g., Windows without admin) don't allow
        # symlinks. Fall back to a "LATEST" marker file. The marker is
        # read by ``read_latest_run_dir()`` below.
        try:
            (link.parent / "LATEST").write_text(target)
        except OSError:
            pass


def read_latest_run_dir(results_dir: Path | None = None) -> Path | None:
    """Resolve the most recent run directory, transparently handling
    symlink OR LATEST-marker fallback.

    Sprint 2 fix 2.7: previously the LATEST marker written by
    ``_safe_mklink`` had no reader in the framework. Now this helper
    transparently handles both cases:

    1. POSIX / Windows-with-admin: ``results/latest`` is a real symlink.
    2. Windows-without-admin: ``results/LATEST`` is a plain file
       containing the run directory name.

    Returns
    -------
    Path or None
        Path to the latest run directory if it exists, else ``None``.
        The directory itself must still exist; if the symlink/marker
        points to a deleted directory, ``None`` is returned.
    """
    results_dir = results_dir if results_dir is not None else _RESULTS_DIR
    latest_link = results_dir / "latest"
    if latest_link.is_symlink():
        # Resolve symlink target relative to its parent.
        try:
            target = (latest_link.parent / latest_link.readlink()).resolve()
            if target.exists():
                return target
        except OSError:
            return None
    # Fallback: LATEST marker file (Windows-without-admin).
    marker = results_dir / "LATEST"
    if marker.is_file():
        target = results_dir / marker.read_text().strip()
        if target.exists():
            return target
    return None


class OutputManager:
    """Manages the standard output directory structure for a run.

    Attributes
    ----------
    path : Path
        The output directory for this run.
    mode : str
        ``"explore"`` or ``"commit"``.
    experiment_name : str
        Name of the experiment being run.
    """

    def __init__(self, experiment_name: str, mode: str = "explore") -> None:
        self.experiment_name = experiment_name
        self.mode = mode

        ts = datetime.now().strftime("%Y-%m-%d_%H%M%S")
        commit = get_git_commit(short=True)
        suffix = f"_{commit}" if commit != "unknown" else ""

        dir_name = f"{ts}_{experiment_name}_{mode}{suffix}"
        self.path = _RESULTS_DIR / dir_name
        self.path.mkdir(parents=True, exist_ok=True)

    def save_metrics(self, metrics: dict[str, Any]) -> Path:
        """Save metrics to ``metrics.json`` with run metadata.

        Adds: timestamp, git_commit, python_version, platform, mode.
        """
        from quant_lib import __version__  # avoid circular at import

        full = {
            "quant_lib_version": __version__,
            "timestamp": datetime.now().isoformat(),
            "git_commit": get_git_commit(short=False),
            "python_version": sys.version.split()[0],
            "platform": platform.platform(),
            "mode": self.mode,
            "experiment": self.experiment_name,
            **metrics,
        }
        path = self.path / "metrics.json"
        path.write_text(json.dumps(full, indent=2, default=str))
        return path

    def save_config(self, experiment: "ExperimentConfig") -> Path:
        """Save the resolved ExperimentConfig to ``config.yaml``."""
        from dataclasses import asdict

        config_dict = {
            "name": experiment.name,
            "strategy_type": experiment.strategy_type,
            "hypothesis": {
                "mechanism": experiment.hypothesis.mechanism,
                "boundary_conditions": experiment.hypothesis.boundary_conditions,
                "success_criteria": experiment.hypothesis.success_criteria,
                "entry_logic": experiment.hypothesis.entry_logic,
                "exit_logic": experiment.hypothesis.exit_logic,
            },
            "period": asdict(experiment.period),
            "universe": asdict(experiment.universe),
            "strategy": asdict(experiment.strategy),
        }
        path = self.path / "config.yaml"
        path.write_text(
            yaml.dump(config_dict, default_flow_style=False, sort_keys=False)
        )
        return path

    def save_html_report(
        self,
        title: str,
        sections: Sequence[tuple],
        subtitle: str = "",
        output_name: str = "report.html",
    ) -> Path:
        """Generate a self-contained HTML report with inline charts.

        ``sections`` is a list of ``(heading, content)`` tuples. Content
        types accepted by ``_render_section`` (str, dict, list of tuples,
        list of lists, or ``("kind", payload)`` dispatch tuples).

        Charts are typically passed as ``("chart", base64_data_uri)``;
        the data URI is embedded inline so the resulting HTML file is
        fully portable (no external image references).

        Parameters
        ----------
        title : str
            Report H1 title.
        sections : list of (heading, content) tuples
            Section content (see ``_render_section``).
        subtitle : str, optional
            Subtitle line under the title.
        output_name : str
            Filename inside the run directory. Default ``"report.html"``.

        Returns
        -------
        Path
            Path to the written report file.
        """
        body_parts = []
        for heading, content in sections:
            body_parts.append(_render_section(heading, content))
        body = "\n".join(body_parts)
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        # Only render the subtitle paragraph if a non-empty subtitle
        # was provided. This avoids a stray empty <p> tag in the output.
        if subtitle:
            subtitle_block = f'<p style="color:#7f8c8d;">{html.escape(subtitle)}</p>'
        else:
            subtitle_block = ""
        html_doc = _HTML_TEMPLATE.format(
            title=html.escape(title),
            subtitle_block=subtitle_block,
            body=body,
            timestamp=ts,
        )
        path = self.path / output_name
        path.write_text(html_doc, encoding="utf-8")
        return path

    def link_latest(self) -> None:
        """Update ``results/latest`` symlink to point to this run."""
        _safe_mklink(_RESULTS_DIR / "latest", self.path.name)
