"""quant_exp init -- Scaffold a new experiment.

Creates a new experiment file in ``quant_lib/experiments/`` from a
template, and optionally writes a ``.env`` file with the required
``QUANT_LIB_HMAC_SECRET`` so the user can start iterating immediately.
"""
from __future__ import annotations

import os
import secrets
import tempfile
from pathlib import Path

import typer

from quant_lib.core._logging import console

# ── Atomic file write helper ──────────────────────────────────────────
# Phase 3.5: crash-safe file writes for scaffold files. A crash
# mid-write should not leave a half-written experiment file or .env
# that is indistinguishable from a complete one.


def _atomic_file_write(path: Path, content: str, encoding: str = "utf-8") -> None:
    """Write ``content`` to ``path`` atomically via tempfile + os.replace.

    A crash mid-write leaves the target file in its original state
    (or creates no file at all). Silent on success.
    """
    dir_name = str(path.parent) if path.parent else "."
    fd, tmp_path = tempfile.mkstemp(
        dir=dir_name, prefix=f".{path.name}_", suffix=".tmp"
    )
    try:
        with os.fdopen(fd, "w", encoding=encoding) as f:
            f.write(content)
        os.replace(tmp_path, str(path))
    except Exception:
        if os.path.exists(tmp_path):
            os.remove(tmp_path)
        raise


# ── Templates ────────────────────────────────────────────────────────────
# Each template is a key phrase (strategy type) → (filename, file content).
# The template content uses ``{name}``, ``{mechanism}``, etc. placeholders
# that are substituted before writing.

_VOL_COMPRESSION_TEMPLATE = '''\
\"\"\"{name}: {mechanism}

Generated by ``quant_exp init``.
\"\"\"
from quant_lib.audit import for_vol_compression
from quant_lib.experiments import (
    PeriodConfig,
    UniverseConfig,
    from_hypothesis,
    register,
)


_HYP = for_vol_compression(
    name="{name}",
    mechanism="{mechanism}",
    boundary_conditions="{boundary_conditions}",
    success_criteria="{success_criteria}",
)


register(from_hypothesis(
    name="{name}",
    hypothesis=_HYP,
    period=PeriodConfig(
        train_start="{train_start}",
        train_end="{train_end}",
        holdout_months={holdout_months},
    ),
    universe=UniverseConfig(
        symbols=[{symbols_list}],
    ),
))
'''

_PULLBACK_TEMPLATE = '''\
\"\"\"{name}: {mechanism}

Generated by ``quant_exp init``.
\"\"\"
from quant_lib.audit import for_pullback_sniper
from quant_lib.experiments import (
    PeriodConfig,
    UniverseConfig,
    from_hypothesis,
    register,
)


_HYP = for_pullback_sniper(
    name="{name}",
    mechanism="{mechanism}",
    boundary_conditions="{boundary_conditions}",
    success_criteria="{success_criteria}",
)


register(from_hypothesis(
    name="{name}",
    hypothesis=_HYP,
    period=PeriodConfig(
        train_start="{train_start}",
        train_end="{train_end}",
        holdout_months={holdout_months},
    ),
    universe=UniverseConfig(
        symbols=[{symbols_list}],
    ),
))
'''

_ENV_TEMPLATE = '''\
# HMAC secret for holdout seal integrity (required).
# Generate with: python -c "import secrets; print(secrets.token_urlsafe(32))"
# Must be >= 32 characters.
{secret_key}=

# Optional: override the holdout seal directory.
# QUANT_LIB_SEAL_DIR=/path/to/seals
'''

_TRAIN_START = "2020-01-01"
_TRAIN_END = "2025-12-31"
_HOLDOUT_MONTHS = 6


def _validate_name(name: str) -> str:
    """Validate and normalise experiment name.

    Raises ``ValueError`` if the name contains characters that would
    be invalid in a Python identifier or filename.
    """
    if not name:
        raise ValueError("Experiment name cannot be empty.")
    if not name[0].isascii() or not (name[0].isalpha() or name[0] == "_"):
        raise ValueError(
            f"Experiment name must start with a letter or underscore, "
            f"got {name[0]!r}."
        )
    allowed = set("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_")
    for ch in name:
        if ch not in allowed:
            raise ValueError(
                f"Character {ch!r} is not allowed in experiment name. "
                f"Use only letters, digits, and underscores."
            )
    return name


def _render_symbols(symbols: list[str]) -> str:
    """Convert symbol list to Python list literal string.

    >>> _render_symbols(["BTCUSDT", "ETHUSDT"])
    '"BTCUSDT", "ETHUSDT"'
    """
    return ", ".join(f'"{s}"' for s in symbols)


def init(
    name: str,
    strategy: str = "vol_compression",
    symbols: str = "BTCUSDT,ETHUSDT,SOLUSDT",
    mechanism: str = "Describe the market mechanism here",
    boundary_conditions: str = "Fails when ...",
    success_criteria: str = "SPA p < 0.15, PF > 1.3, min 30 trades",
    train_start: str = _TRAIN_START,
    train_end: str = _TRAIN_END,
    holdout_months: int = _HOLDOUT_MONTHS,
    generate_env: bool = True,
) -> None:
    """Scaffold a new experiment file and optional .env template.

    Parameters
    ----------
    name : str
        Experiment name (Python identifier, e.g. ``my_strategy``).
        This becomes the filename and the registry key.
    strategy : str
        Strategy type: ``"vol_compression"`` (default) or
        ``"pullback_sniper"``.
    symbols : str
        Comma-separated symbol list (default ``BTCUSDT,ETHUSDT,SOLUSDT``).
    mechanism : str
        Description of the market mechanism the strategy exploits.
    boundary_conditions : str
        Conditions where the strategy is expected to fail.
    success_criteria : str
        Criteria for a successful commit (SPA, PF, min trades, etc.).
    train_start : str
        Training start date (YYYY-MM-DD). Default 2020-01-01.
    train_end : str
        Training end date (YYYY-MM-DD). Default 2025-12-31.
    holdout_months : int
        Holdout duration in months (auto-resolved from train_end + 1d).
        Default 6.
    generate_env : bool
        If True (default), generate a ``.env`` file with the
        ``QUANT_LIB_HMAC_SECRET`` variable filled in with a random key.
    """
    # Validate inputs
    try:
        name = _validate_name(name)
    except ValueError as e:
        console.print(f"[red]Error:[/red] {e}")
        raise typer.Exit(code=1) from e
    symbol_list = [s.strip() for s in symbols.split(",") if s.strip()]

    # Select template
    if strategy == "vol_compression":
        template = _VOL_COMPRESSION_TEMPLATE
    elif strategy == "pullback_sniper":
        template = _PULLBACK_TEMPLATE
    else:
        raise ValueError(
            f"Unknown strategy type {strategy!r}. "
            f"Supported: vol_compression, pullback_sniper."
        )

    # Render template
    content = template.format(
        name=name,
        mechanism=mechanism,
        boundary_conditions=boundary_conditions,
        success_criteria=success_criteria,
        train_start=train_start,
        train_end=train_end,
        holdout_months=holdout_months,
        symbols_list=_render_symbols(symbol_list),
    )

    # Write the experiment file
    exp_dir = Path("quant_lib/experiments")
    exp_dir.mkdir(parents=True, exist_ok=True)
    exp_file = exp_dir / f"{name}.py"
    if exp_file.exists():
        console.print(
            f"[yellow]Experiment file already exists:[/yellow] {exp_file}"
        )
        return

    _atomic_file_write(exp_file, content, encoding="utf-8")
    console.print(f"[green]Created[/green] {exp_file}")

    # Write .env template
    if generate_env:
        env_file = Path(".env")
        if env_file.exists():
            console.print(
                f"[yellow]Skipped .env (already exists):[/yellow] {env_file}"
            )
        else:
            env_content = _ENV_TEMPLATE.format(
                secret_key="QUANT_LIB_HMAC_SECRET",
            ).replace("=\n", f"={secrets.token_urlsafe(32)}\n")
            _atomic_file_write(env_file, env_content, encoding="utf-8")
            console.print(
                f"[green]Created[/green] {env_file} "
                f"(with random HMAC secret)"
            )

    # Print next steps
    console.print()
    console.print("[bold]Next steps:[/bold]")
    console.print(f"  1. Edit [bold]{exp_file}[/bold] to customise")
    if generate_env:
        console.print(
            "  2. Run [bold]source .env[/bold] (Linux/Mac) or "
            "[bold].\\.env.ps1[/bold] (Windows) to set the HMAC secret"
        )
    console.print(f"  3. Run [bold]quant_exp show {name}[/bold] to verify")
    console.print(f"  4. Run [bold]quant_exp explore {name}[/bold] to test")
